<h1>Inscription</h1>

<form action="register.php" method="post">
    <div class="form-group">
        <label for="username">Votre pseudo</label>
        <input id="username" name="username" type="text" class="form-control">
    </div>
    <div class="form-group">
        <label for="email">Email</label>
        <input id="email" name="email" type="email" class="form-control">
    </div>
    <div class="form-group">
        <label for="password">Mot de passe</label>
        <input id="password" name="password" type="password" class="form-control">
    </div>
    <button class="btn btn-primary">S'inscrire</button>
</form>